---
# Codacy configuration for DentSignal
# Reduces noise from Pylint and DevSkim by excluding non-production files
# and configuring appropriate rule severities.

engines:
  pylint:
    enabled: true
    # Only analyze production code, not tests/docs/scripts
    exclude_paths:
      - "dental_agent/tests/**"
      - "dental_agent/test_*.py"
      - "dental_agent/archive/**"
      - "dental_agent/__pycache__/**"
      - "dental_agent/logs/**"
      - "dental_agent/websocket_bridge_old.py"
      - "dashboard/tests/**"
      - "dashboard/test-results/**"
      - "dashboard/.next/**"
      - "dashboard/node_modules/**"
      - "dentsignal/**"
      - "docs/**"
      - "scripts/**"
      - "plans/**"
      - "openspec/**"
      - "brand/**"
      - "*.md"
      - "*.sh"
      - "*.bat"
      - "*.ps1"
    # Use our .pylintrc which disables noisy rules
    python_version: 3
  devskim:
    enabled: false
  # ESLint rules are handled by the dashboard's own eslint config
  eslint:
    enabled: false

# Global exclusions - these paths are never analyzed by ANY tool
exclude_paths:
  - "dental_agent/tests/**"
  - "dental_agent/test_*.py"
  - "dental_agent/test_voice_agent.py"
  - "dental_agent/test_api.py"
  - "dental_agent/test_agent_responses.py"
  - "dental_agent/test_ai_providers.py"
  - "dental_agent/test_api_key.py"
  - "dental_agent/test_deepgram_connection.py"
  - "dental_agent/archive/**"
  - "dental_agent/__pycache__/**"
  - "dental_agent/logs/**"
  - "dental_agent/websocket_bridge_old.py"
  - "dental_agent/check_db.py"
  - "dental_agent/verify_all_apis.py"
  - "dashboard/tests/**"
  - "dashboard/test-results/**"
  - "dashboard/.next/**"
  - "dashboard/node_modules/**"
  - "dentsignal/**"
  - "docs/**"
  - "scripts/**"
  - "plans/**"
  - "openspec/**"
  - "brand/**"
  - ".devskim.json"
  - ".github/**"
  - "*.md"
  - "*.bat"
  - "*.ps1"
  - "*.sh"
  - "*.sh"
