---
# Codacy configuration for DentSignal
# Reduces noise from Pylint and DevSkim by excluding non-production files
# and configuring appropriate rule severities.

engines:
  pylint:
    enabled: true
    # Only analyze production code, not tests/docs/scripts
    exclude_paths:
      - "dental_agent/tests/**"
      - "dental_agent/test_*.py"
      - "dental_agent/archive/**"
      - "dental_agent/__pycache__/**"
      - "dashboard/tests/**"
      - "dashboard/test-results/**"
      - "dentsignal/**"
      - "docs/**"
      - "scripts/**"
      - "plans/**"
      - "openspec/**"
      - "brand/**"
      - "*.md"
  devskim:
    enabled: true
    exclude_paths:
      - "dental_agent/tests/**"
      - "dental_agent/test_*.py"
      - "dental_agent/archive/**"
      - "dashboard/tests/**"
      - "dashboard/test-results/**"
      - "dentsignal/**"
      - "docs/**"
      - "scripts/**"
      - "plans/**"
      - "openspec/**"
      - "brand/**"
      - "*.md"

# Global exclusions - these paths are never analyzed
exclude_paths:
  - "dental_agent/tests/**"
  - "dental_agent/test_*.py"
  - "dental_agent/test_voice_agent.py"
  - "dental_agent/test_api.py"
  - "dental_agent/test_agent_responses.py"
  - "dental_agent/test_ai_providers.py"
  - "dental_agent/test_api_key.py"
  - "dental_agent/test_deepgram_connection.py"
  - "dental_agent/archive/**"
  - "dental_agent/__pycache__/**"
  - "dental_agent/logs/**"
  - "dashboard/tests/**"
  - "dashboard/test-results/**"
  - "dashboard/.next/**"
  - "dashboard/node_modules/**"
  - "dentsignal/**"
  - "docs/**"
  - "scripts/**"
  - "plans/**"
  - "openspec/**"
  - "brand/**"
  - "*.md"
  - "*.bat"
  - "*.ps1"
  - "*.sh"
